# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appredirectstate',
            name='user_integration',
        ),
        migrations.RemoveField(
            model_name='quickbooksusertoken',
            name='user_integration',
        ),
        migrations.RemoveField(
            model_name='yellowantredirectstate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yellowusertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppRedirectState',
        ),
        migrations.DeleteModel(
            name='QuickbooksUserToken',
        ),
        migrations.DeleteModel(
            name='YellowAntRedirectState',
        ),
        migrations.DeleteModel(
            name='YellowUserToken',
        ),
    ]
