# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_quickbookusertoken_idtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookusertoken',
            name='realmID',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
