# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180601_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realmId', models.CharField(max_length=512)),
                ('user_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken')),
            ],
        ),
        migrations.RemoveField(
            model_name='quickbookusertoken',
            name='realmID',
        ),
    ]
