# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20180601_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yellowusertoken',
            name='user',
            field=models.IntegerField(),
        ),
    ]
