# Generated by Django 2.0.6 on 2018-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_quickbookusertoken_login_update_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowusertoken',
            name='realmId',
            field=models.CharField(default='', max_length=512),
        ),
    ]
