# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_quickbookusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbookusertoken',
            name='accessToken',
            field=models.CharField(max_length=32768),
        ),
    ]
