# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180601_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickbookusertoken',
            name='idToken',
        ),
    ]
