# Generated by Django 2.0.6 on 2018-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_quickbookusertoken_realmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yellowusertoken',
            name='user',
            field=models.IntegerField(),
        ),
    ]
