# Generated by Django 2.0.6 on 2018-06-15 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20180614_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookusertoken',
            name='accessToken_last_refreshed',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
